# Generated by Django 4.2.13 on 2025-05-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembership",
            name="character",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="wod20th.charactersheet",
            ),
        ),
    ]
