# Generated by Django 4.2.13 on 2025-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_viewed",
            field=models.JSONField(default=dict),
        ),
    ]
