# Generated by Django 4.2.16 on 2025-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_viewed",
            field=models.JSONField(default=dict),
        ),
    ]
