"""
This module contains the restrictions for specific gifts by shifter type.

The restrictions are stored in a dictionary where the key is the gift name
and the value is a dictionary containing the shifter type and the minimum level
at which the gift is restricted.
The following format is used for general restrictions:
'Gift Name': {'Shifter Type': minimum_level}
For example, the gift 'Spirit of the Lizard' is a level two Ratkin gift.
All Ratkin can take this gift at level 2 and it counts as in-breed.

Some gifts are further restricted to specific tribes, breeds, aspects, or auspices at certain levels,
this has the following format: 
'Gift Name': {'Shifter Type': {'Restriction': minimum_level}}
For example, the gift 'Eye of the Hunter' is a general Ajaba gift and has no additional restrictions (in-breed for all Ajaba),
however, the gift 'Sweet Hunter\'s Smile' is a level one Homid Bastet gift, so is only in-breed for Bastet with the 'breed' of Homid.

"""
SHIFTER_GIFT_RESTRICTIONS = {

    # Ajaba restrictions
    'Red Talon': {'Ajaba': 1},
    'Wolf at the Door': {'Ajaba': 1},
    'Infectious Laughter': {'Ajaba': 1},
    'Primal Anger': {'Ajaba': 1},
    'Sense Prey': {'Ajaba': 1},
    'Curse of Hatred': {'Ajaba': 2},
    'Man\'s Skin': {'Ajaba': 2},
    'Odious Aroma': {'Ajaba': 2},
    'Pulse of the Prey': {'Ajaba': 2},
    'Clenched Jaw': {'Ajaba': 3},
    'Gift of the Skunk': {'Ajaba': 3},
    'Laugh of the Hyena': {'Ajaba': 3},
    'Gnaw': {'Ajaba': 4},
    'Gorge': {'Ajaba': 4},
    'Endurance of Heimdall': {'Ajaba': 5},
    'Survivor': {'Ajaba': 5},
    'Withering Stare': {'Ajaba': 5},
    'Beat of the Heart-Drum': {'Ajaba': 1},
    'Lightning Reflexes': {'Ajaba': 1},
    'Pack Tactics': {'Ajaba': 1},
    'Razor Claws': {'Ajaba': 1},
    'Resist Pain': {'Ajaba': 1},
    'Sense Wyrm': {'Ajaba': 1},
    'Command Spirit': {'Ajaba': 2},
    'Flame Dance': {'Ajaba': 2},
    'Shield of Rage': {'Ajaba': 2},
    'Spirit of the Fray': {'Ajaba': 2},
    'Bloody Feast': {'Ajaba': 3},
    'Redirect Pain': {'Ajaba': 3},
    'Sense the Unnatural': {'Ajaba': 3},
    'Silver Claws': {'Ajaba': 3},
    'Grasp the Beyond': {'Ajaba': 4},
    'Stoking Fury\'s Furnace': {'Ajaba': 4},
    'Fenris\' Bite': {'Ajaba': 5},
    'Strength of Will': {'Ajaba': 5},
    'Beast Speech': {'Ajaba': 1},
    'Mindspeak': {'Ajaba': 1},
    'Mother\'s Touch': {'Ajaba': 1},
    'Perfect Recall': {'Ajaba': 1},
    'Persuasion': {'Ajaba': 1},
    'Distractions': {'Ajaba': 2},
    'Dreamspeak': {'Ajaba': 2},
    'Faerie Kin': {'Ajaba': 3},
    'Exorcism': {'Ajaba': 3},
    'Song of Heroes': {'Ajaba': 3},
    'Wisdom of the Ancient Ways': {'Ajaba': 3},
    'Gift of Dreams': {'Ajaba': 4},
    'Phantasm': {'Ajaba': 4},
    'Fabric of the Mind': {'Ajaba': 5},
    'Blur of the Milky Eye': {'Ajaba': 1},
    'Fatal Flaw': {'Ajaba': 1},
    'Open Seal': {'Ajaba': 1},
    'Scent of Running Water': {'Ajaba': 1},
    'Spirit Snare': {'Ajaba': 1},
    'Spirit Speech': {'Ajaba': 1},
    'Blissful Ignorance': {'Ajaba': 2},
    'Luna\'s Armor': {'Ajaba': 2},
    'Sight From Beyond': {'Ajaba': 2},
    'Taking the Forgotten': {'Ajaba': 2},
    'Paralyzing Stare': {'Ajaba': 3},
    'Pulse of the Invisible': {'Ajaba': 3},
    'Backbite': {'Ajaba': 3},
    'Open Wounds': {'Ajaba': 4},
    'Reach the Umbra': {'Ajaba': 5},
    'Shadow Pack': {'Ajaba': 5},
    'Friend in Need': {'Ajaba': 3},
    
    # Ananasi restrictions
    'Balance': {'Ananasi': 1},
    'Spirit of the Lizard': {'Ananasi': 1},
    'Resist Pain': {'Ananasi': 1},
    'Resist Toxin': {'Ananasi': 1},
    'Gift of the Porcupine': {'Ananasi': 2},
    'Great Leap': {'Ananasi': 3},
    'Catfeet': {'Ananasi': 3},
    'Survivor': {'Ananasi': 5},
    'Predator\'s Patience': {'Ananasi': 1},
    'Eye of the Cobra': {'Ananasi': 3},
    'Reshape Object': {'Ananasi': 3},
    'Thieving Talons of the Magpie': {'Ananasi': 5},
    'Call of the Wyrm': {'Ananasi': 2},
    'Pulse of the Invisible': {'Ananasi': 3},
    'Breath of the Wyld': {'Ananasi': 1},
    'Mother\'s Touch': {'Ananasi': 1},
    'Sight From Beyond': {'Ananasi': 2},
    'Scent of Sight': {'Ananasi': 3},
    'Mindblock': {'Ananasi': 4},
    'Feral Lobotomy': {'Ananasi': 4},
    'Assimilation': {'Ananasi': 5},
    'Icy Chill of Despair': {'Ananasi': 1},
    'Open Seal': {'Ananasi': 1},
    'Hydraulic Strength': {'Ananasi': 2},
    'True Fear': {'Ananasi': 2},
    'Weak Arm': {'Ananasi': 3},
    'Pulse of the Prey': {'Ananasi': 4},
    'Whelp Body': {'Ananasi': 4},
    'Shroud': {'Ananasi': 1},
    'Mindspeak': {'Ananasi': 2},
    'Cocoon': {'Ananasi': 3},
    'Attunement': {'Ananasi': 4},
    'Shattering': {'Ananasi': 5},
    'Beast Mind': {'Ananasi': 1},
    'Visceral Agony': {'Ananasi': 2},
    'Wither Limb': {'Ananasi': 4},
    'Summon Net-Spider': {'Ananasi': 5},
    'Burrow': {'Ananasi': 2},
    'Hydraulic Strength': {'Ananasi': 2},
    'Scent of Sweet Honey': {'Ananasi': 2},
    'Minor Unweaving': {'Ananasi': 3},
    'Minor Unweaving': {'Ananasi': 4},
    'Beast Mind': {'Ananasi': 1},
    'Tick Body': {'Ananasi': 3},

    # Bastet restrictions
    'Catfeet': {'Bastet': 1},
    'Razor Claws': {'Bastet': 1},
    'Mother\'s Touch': {'Bastet': 1},
    'Open Seal': {'Bastet': 1},
    'Sense Magic': {'Bastet': 1},
    'Truth of Gaia': {'Bastet': 1},
    'Sense Wyrm': {'Bastet': 1},
    'Eyes of the Cat': {'Bastet': 2},
    'Staredown': {'Bastet': 2},
    'Spirit of the Fray': {'Bastet': 2},
    'Pulse of the Prey': {'Bastet': 2},
    'Sense Silver': {'Bastet': 2},
    'Taking the Forgotten': {'Bastet': 2},
    'Scrying': {'Bastet': 3},
    'Invisibility': {'Bastet': 3},
    'Mental Speech': {'Bastet': 3},
    'Silver Claws': {'Bastet': 4},
    'Persuasion': {'Bastet': {'Homid': 1}},
    'City Running': {'Bastet': {'Homid': 1}},
    'Whisper Catching': {'Bastet': {'Shadow Lord': 2}},
    'Jam Technology': {'Bastet': {'Homid': 2}},
    'Cowing the Bullet': {'Bastet': {'Homid': 3}},
    'Reshape Object': {'Bastet': {'Homid': 3}},
    'Doppelganger': {'Bastet': {'Homid': 4}},
    'Tech Speak': {'Bastet': {'Homid': 4}},
    'Madness': {'Bastet': {'Metis': 5}},
    'Create Element': {'Bastet': {'Metis': 1}},
    'Sense Wyrm': {'Bastet': {'Metis': 1}},
    'Shed': {'Bastet': {'Metis': 1}},
    'Visceral Agony': {'Bastet': {'Metis': 3}},
    'Open Moon Bridge': {'Bastet': {'Metis': 4}},
    'Divine Wind': {'Bastet': {'Metis': 5}},
    'Heightened Senses': {'Bastet': {'Feline': 1}},
    'Hare\'s Leap': {'Bastet': {'Feline': 1}},
    'Catfeet': {'Bastet': {'Feline': 2}},
    'Monkey Tail': {'Bastet': {'Feline': 2}},
    'Chains of Mist': {'Bastet': {'Feline': 3}},
    'Fatal Flaw': {'Bastet': {'Feline': 3}},
    'Beast Life': {'Bastet': {'Feline': 4}},
    'Gaia\'s Vengeance': {'Bastet': {'Feline': 5}},
    'Balance': {'Bastet': {'Bagheera': 1}},
    'Command the Gathering': {'Bastet': {'Bagheera': 2}},
    'Eye of the Cobra': {'Bastet': {'Bagheera': 3}},
    'Weak Arm': {'Bastet': {'Bagheera': 3}},
    'Curse of Aeolus': {'Bastet': {'Balam': 1}},
    'Scent of Sweet Honey': {'Bastet': {'Balam': 1}},
    'Pathfinder': {'Bastet': {'Balam': 2}},
    'True Fear': {'Bastet': {'Balam': 2}},
    'Wings of Pegasus': {'Bastet': {'Balam': 3}},
    'Trackless Waste': {'Bastet': {'Balam': 3}},
    'Dreamspeak': {'Bastet': {'Balam': 2}},
    'Spirit Ward': {'Bastet': {'Balam': 2}},
    'Coils of the Serpent': {'Bastet': {'Balam': 4}},
    'Shadow Pack': {'Bastet': {'Balam': 5}},
    'Faerie Light': {'Bastet': {'Ceilican': 1}},
    'Master of Fire': {'Bastet': {'Ceilican': 2}},
    'Faerie Kin': {'Bastet': {'Ceilican': 3}},
    'Phantasm': {'Bastet': {'Ceilican': 3}},
    'Gift of Dreams': {'Bastet': {'Ceilican': 4}},
    'Riot': {'Bastet': {'Ceilican': 5}},
    'Heart of Fury': {'Bastet': {'Khan': 2}},
    'Banish Cahlash\'s Brood': {'Bastet': {'Khan': 3}},
    'Voice of the Mimic': {'Bastet': {'Pumonca': 1}},
    'Speak with Wind Spirits': {'Bastet': {'Pumonca': 2}},
    'Spirit of the Fish': {'Bastet': {'Pumonca': 2}},
    'Quicksand': {'Bastet': {'Pumonca': 3}},
    'Call Elemental': {'Bastet': {'Pumonca': 4}},
    'Divine Wind': {'Bastet': {'Pumonca': 5}},
    'Wanderer\'s Boon': {'Bastet': {'Qualmi': 1}},
    'Song of the Earth Mother': {'Bastet': {'Qualmi': 3}},
    'Wisdom of the Ancient Ways': {'Bastet': {'Qualmi': 3}},
    'Chill of Early Frost': {'Bastet': {'Qualmi': 4}},
    'King Fish': {'Bastet': {'Simba': 1}},
    'Kneel': {'Bastet': {'Simba': 1}},
    'Luna\'s Armor': {'Bastet': {'Simba': 2}},
    'Might of Thor': {'Bastet': {'Simba': 2}},
    'Coup de Grace': {'Bastet': {'Simba': 3}},
    'Wrath of Gaia': {'Bastet': {'Simba': 3}},
    'Obedience': {'Bastet': {'Simba': 5}},
    'Blissful Ignorance': {'Bastet': {'Swara': 1}},
    'Speed of Thought': {'Bastet': {'Swara': 1}},
    'Sense the Unnatural': {'Bastet': {'Swara': 2}},
    'Walking Between Worlds': {'Bastet': {'Swara': 2}},
    'Messenger\'s Fortitude': {'Bastet': {'Swara': 3}},
    'Speed Beyond Thought': {'Bastet': {'Swara': 3}},
    'Perfect Cover': {'Bastet': {'Balam': 2}},
    'Redeem the Waste': {'Bastet': {'Balam': 5}},
    'Babel\'s Cure': {'Bastet': {'Bubasti': 3}},
    'Shadowplay': {'Bastet': {'Bubasti': 4}},
    'Deny the Hungry': {'Bastet': {'Bubasti': 5}},
    'Data Flow': {'Bastet': {'Celican': 3}},
    'Snarl of the Predator': {'Bastet': {'Khan': 2}},
    'Reshape Object': {'Bastet': {'Khan': 3}},
    'Strength of Will': {'Bastet': {'Khan': 5}},
    'Reshape Object': {'Bastet': {'Pumonca': 2}},
    'Camouflage': {'Bastet': {'Qualmi': 1}},
    'Cheshire Prank': {'Bastet': {'Qualmi': 3}},
    'Open Moon Bridge': {'Bastet': {'Qualmi': 4}},
    'Dragonroar': {'Bastet': {'Simba': 3}},
    'King of Beasts': {'Bastet': {'Simba': 4}},
    'Impala\'s Flight': {'Bastet': {'Swara': 1}},
    'Judgment of Pestilence': {'Bastet': {'Swara': 4}},
    'The Thousand Forms': {'Bastet': {'Black Fury': 5}},

    # Corax restrictions
    'Open Seal': {'Corax': 1},
    'Persuasion': {'Corax': 1},
    'Scent of the True Form': {'Corax': 1},
    'Spirit Speech': {'Corax': 1},
    'Truth of Gaia': {'Corax': 1},
    'Messenger\'s Fortitude': {'Corax': 2},
    'Speech of the World': {'Corax': 2},
    'Taking the Forgotten': {'Corax': 2},
    'Whisper Catching': {'Corax': 2},
    'Spider\'s Song': {'Corax': 2},
    'Scrying': {'Corax': 3},
    'Sense the Unnatural': {'Corax': 3},
    'Attunement': {'Corax': 4},
    'Airt Sense': {'Corax': 4},
    'Kiss of Helios': {'Corax': 4},
    'Desperate Strength': {'Corax': 1},
    'Healing Tongue': {'Corax': 1},
    'Ignore Wounds': {'Corax': 1},
    'Sense Pattern Breaker': {'Corax': 1},
    'Sentinel\'s Warning': {'Corax': 1},
    'Tongues': {'Corax': 2},

    # Gurahl restrictions
    'Desperate Strength': {'Gurahl': 1},
    'Mother\'s Touch': {'Gurahl': 1},
    'Resist Pain': {'Gurahl': 1},
    'Sense Wyrm': {'Gurahl': 1},
    'Danger Sense': {'Gurahl': 1},
    'Resist Toxin': {'Gurahl': 1},
    'Wyld Resurgence': {'Gurahl': 1},
    'Calm': {'Gurahl': 2},
    'True Fear': {'Gurahl': 2},
    'Para Bellum': {'Gurahl': 2},
    'Lover\'s Touch': {'Gurahl': 3},
    'Adaptation': {'Gurahl': 3},
    'Heart of the Mountain': {'Gurahl': 4},
    'Bury the Wolf': {'Gurahl': 4},
    'Master of Fire': {'Gurahl': 1},
    'Persuasion': {'Gurahl': {'Homid': 1}},
    'Staredown': {'Gurahl': {'Homid': 2}},
    'Reshape Object': {'Gurahl': {'Homid': 3}},
    'Spirit Ward': {'Gurahl': {'Homid': 4}},
    'Cocoon': {'Gurahl': {'Homid': 4}},
    'Part the Veil': {'Gurahl': {'Homid': 5}},
    'Create Element': {'Gurahl': {'Ursine': 1}},
    'Heightened Senses': {'Gurahl': {'Ursine': 1}},
    'Burrow': {'Gurahl': {'Ursine': 2}},
    'Gnaw': {'Gurahl': {'Ursine': 4}},
    'Scent of Sweet Honey': {'Gurahl': {'Ursine': 4}},
    'Totem Gift': {'Gurahl': {'Ursine': 5}},
    'Song of the Great Beast': {'Gurahl': {'Ursine': 5}},
    'Open Seal': {'Gurahl': {'Arcas': 1}},
    'Pulse of the Prey': {'Gurahl': {'Arcas': 2}},
    'Trackless Waste': {'Gurahl': {'Arcas': 3}},
    'Luna\'s Blessing': {'Gurahl': {'Arcas': 4}},
    'Breath of the Wyld': {'Gurahl': {'Arcas': 4}},
    'Razor Claws': {'Gurahl': {'Uzmati': 1}},
    'Silver Claws': {'Gurahl': {'Uzmati': 3}},
    'Hero\'s Stand': {'Gurahl': {'Uzmati': 4}},
    'Beast Speech': {'Gurahl': {'Kojubat': 1}},
    'Mindspeak': {'Gurahl': {'Kojubat': 3}},
    'Scent of the True Form': {'Gurahl': {'Kojubat': 2}},
    'Spirit Speech': {'Gurahl': {'Kojubat': 1}},
    'Sense the Unnatural': {'Gurahl': {'Kojubat': 2}},
    'Exorcism': {'Gurahl': {'Kojubat': 3}},
    'Name the Spirit': {'Gurahl': {'Kojubat': 3}},
    'Truth of Gaia': {'Gurahl': {'Kojubat': 1}},
    'Geas': {'Gurahl': {'Kojubat': 5}},
    'Shadows by the Fire Light': {'Gurahl': {'Kojubat': 4}},

    # Kitsune restrictions
    'Mindspeak': {'Kitsune': 1},
    'Scent of Running Water': {'Kitsune': 1},
    'Sense Magic': {'Kitsune': 2},
    'Spirit Speech': {'Kitsune': 2},
    'Persuasion': {'Kitsune': {'Kojin': 1}},
    'Smell of Man': {'Kitsune': {'Kojin': 1}},
    'Jam Technology': {'Kitsune': {'Kojin': 2}},
    'Glib Tongue': {'Kitsune': {'Kojin': 2}},
    'Staredown': {'Kitsune': {'Kojin': 2}},
    'Disquiet': {'Kitsune': {'Kojin': 3}},
    'Reshape Object': {'Kitsune': {'Kojin': 3}},
    'Speech of the World': {'Kitsune': {'Kojin': 3}},
    'Spirit Ward': {'Kitsune': {'Kojin': 4}},
    'Assimilation': {'Kitsune': {'Kojin': 5}},
    'Burrow': {'Kitsune': {'Kojin': 1}},
    'Hare\'s Leap': {'Kitsune': {'Kojin': 1}},
    'Heightened Senses': {'Kitsune': {'Kojin': 1}},
    'Name the Spirit': {'Kitsune': {'Kojin': 2}},
    'Scent of Sight': {'Kitsune': {'Kojin': 2}},
    'Catfeet': {'Kitsune': {'Kojin': 3}},
    'Beast Life': {'Kitsune': {'Kojin': 4}},
    'Elemental Gift': {'Kitsune': {'Kojin': 5}},
    'Song of the Great Beast': {'Kitsune': {'Kojin': 5}},
    'Scent of the True Form': {'Kitsune': {'Shinju': 1}},
    'Sense Wyrm': {'Kitsune': {'Shinju': 1}},
    'Call to Duty': {'Kitsune': {'Shinju': 2}},
    'Mental Speech': {'Kitsune': {'Shinju': 3}},
    'Eyes of the Cat': {'Kitsune': {'Shinju': 3}},
    'Wisdom of the Ancient Ways': {'Kitsune': {'Shinju': 3}},
    'Roll Over': {'Kitsune': {'Shinju': 4}},
    'Scent of Beyond': {'Kitsune': {'Shinju': 4}},
    'Geas': {'Kitsune': {'Shinju': 5}},
    'Curse of Aeolus': {'Kitsune': {'Shinju': 1}},
    'Sense Wyrm': {'Kitsune': {'Shinju': 1}},
    'Shroud': {'Kitsune': {'Shinju': 1}},
    'Spirit Snare': {'Kitsune': {'Shinju': 1}},
    'Command Spirit': {'Kitsune': {'Shinju': 2}},
    'Name the Spirit': {'Kitsune': {'Shinju': 2}},
    'Shadows at Dawn': {'Kitsune': {'Shinju': 2}},
    'Sight from Beyond': {'Kitsune': {'Shinju': 2}},
    'Exorcism': {'Kitsune': {'Shinju': 3}},
    'Pulse of the Invisible': {'Kitsune': {'Shinju': 3}},
    'Grasp the Beyond': {'Kitsune': {'Shinju': 4}},
    'Spirit Drain': {'Kitsune': {'Shinju': 4}},
    'Spirit Ward': {'Kitsune': {'Shinju': 4}},
    'Feral Lobotomy': {'Kitsune': {'Shinju': 5}},
    'Malleable Spirit': {'Kitsune': {'Shinju': 5}},
    
    # Kitsune Eji Gifts
    'Falling Touch': {'Kitsune': {'Eji': 1}},
    'Razor Claws': {'Kitsune': {'Eji': 1}},
    'Resist Pain': {'Kitsune': {'Eji': 1}},
    'Pulse of the Prey': {'Kitsune': {'Eji': 2}},
    'Spirit of the Fray': {'Kitsune': {'Eji': 2}},
    'Weak Arm': {'Kitsune': {'Eji': 3}},
    'Song of the Great Beast': {'Kitsune': {'Eji': 5}},
    'Kiss of Helios': {'Kitsune': {'Eji': 5}},
    
    # Kitsune Gukutsushi Gifts
    'Blur of the Milky Eye': {'Kitsune': {'Gukutsushi': 1}},
    'Calm': {'Kitsune': {'Gukutsushi': 1}},
    'Mother\'s Touch': {'Kitsune': {'Gukutsushi': 1}},
    'Open Seal': {'Kitsune': {'Gukutsushi': 1}},
    'Dreamspeak': {'Kitsune': {'Gukutsushi': 2}},
    'Glib Tongue': {'Kitsune': {'Gukutsushi': 2}},
    'Taking the Forgotten': {'Kitsune': {'Gukutsushi': 2}},
    'Mental Speech': {'Kitsune': {'Gukutsushi': 3}},
    'Gremlins': {'Kitsune': {'Gukutsushi': 3}},
    'Liar\'s Craft': {'Kitsune': {'Gukutsushi': 3}},
    'Doppelganger': {'Kitsune': {'Gukutsushi': 4}},
    'Whelp Body': {'Kitsune': {'Gukutsushi': 4}},
    'Madness': {'Kitsune': {'Gukutsushi': 5}},
    'Fog on the Moor': {'Kitsune': {'Gukutsushi': 5}},
    
    # Kitsune Kataribe Gifts
    'Beast Speech': {'Kitsune': {'Kataribe': 1}},
    'Perfect Recall': {'Kitsune': {'Kataribe': 1}},
    'Truth of Gaia': {'Kitsune': {'Kataribe': 1}},
    'Call of the Wyrm': {'Kitsune': {'Kataribe': 2}},
    'Distractions': {'Kitsune': {'Kataribe': 2}},
    'Speech of the World': {'Kitsune': {'Kataribe': 2}},
    'Tongues': {'Kitsune': {'Kataribe': 2}},
    'Wisdom of the Ancient Ways': {'Kitsune': {'Kataribe': 3}},
    'Shadows by the Firelight': {'Kitsune': {'Kataribe': 4}},
    'Assimilation': {'Kitsune': {'Kataribe': 5}},
    'Fabric of the Mind': {'Kitsune': {'Kataribe': 5}},
    
    # Kitsune Ju-Fu Gifts
    'Thousand Forms': {'Kitsune': {'Ju-Fu': 4}},
    'Paper Beast': {'Kitsune': {'Ju-Fu': 5}},

    # Mokole General Gifts
    'Falling Touch': {'Mokole': 1},
    'Fatal Flaw': {'Mokole': 1},
    'Inspiration': {'Mokole': 1},
    'Razor Claws': {'Mokole': 1},
    'Sense Wyrm': {'Mokole': 1},
    'Shed': {'Mokole': 1},
    'Scent of the True Form': {'Mokole': 1},
    'Speed of Thought': {'Mokole': 1},
    'Sense Silver': {'Mokole': 2},
    'Silver Claws': {'Mokole': 2},
    'Odious Aroma': {'Mokole': 2},
    'True Fear': {'Mokole': 3},
    'Attunement': {'Mokole': 4},
    'Cocoon': {'Mokole': 4},
    'Serenity': {'Mokole': 4},
    'Grasp the Beyond': {'Mokole': 5},
    'Song of the Great Beast': {'Mokole': 5},
    'Scent of Sweet Honey': {'Mokole': 1},
    'Sense Prey': {'Mokole': 1},
    'Trackless Waste': {'Mokole': 2},
    'Avalanche': {'Mokole': 4},
    
    # Mokole Rising Sun Gifts
    'Master of Fire': {'Mokole': {'Rising Sun': 1}},
    'Sense Silver': {'Mokole': {'Rising Sun': 2}},
    'Combat Healing': {'Mokole': {'Rising Sun': 3}},
    'Thunderbolt': {'Mokole': {'Rising Sun': 3}},
    'Render Down': {'Mokole': {'Rising Sun': 3}},
    'Invoke the Spirits of the Storm': {'Mokole': {'Rising Sun': 4}},
    'Scream of Gaia': {'Mokole': {'Rising Sun': 4}},
    'Wall of Granite': {'Mokole': {'Rising Sun': 5}},
    
    # Mokole Noonday Sun Gifts
    'Fangs of Judgment': {'Mokole': {'Noonday Sun': 1}},
    'Persuasion': {'Mokole': {'Noonday Sun': 1}},
    'Truth of Gaia': {'Mokole': {'Noonday Sun': 1}},
    'Calm': {'Mokole': {'Noonday Sun': 2}},
    'Strength of Purpose': {'Mokole': {'Noonday Sun': 2}},
    'Weak Arm': {'Mokole': {'Noonday Sun': 3}},
    'Eye of the Cobra': {'Mokole': {'Noonday Sun': 3}},
    'Wisdom of the Seer': {'Mokole': {'Noonday Sun': 5}},
    'Balor\'s Gaze': {'Mokole': {'Noonday Sun': 4}},
    'Strength of the Dominator': {'Mokole': {'Noonday Sun': 4}},
    'Geas': {'Mokole': {'Noonday Sun': 5}},
    'Burrow': {'Mokole': {'Noonday Sun': 1}},
    'Mother\'s Touch': {'Mokole': {'Noonday Sun': 1}},
    'Resist Pain': {'Mokole': {'Noonday Sun': 1}},
    'Clap of Thunder': {'Mokole': {'Noonday Sun': 2}},
    'Paint the Meadows': {'Mokole': {'Noonday Sun': 2}},
    'Fu Xi\'s Honor': {'Mokole': {'Noonday Sun': 2}},
    'Flame Dance': {'Mokole': {'Noonday Sun': 2}},
    'Clarity': {'Mokole': {'Noonday Sun': 3}},
    'Combat Healing': {'Mokole': {'Noonday Sun': 3}},
    'Might of Thor': {'Mokole': {'Noonday Sun': 3}},
    'Clenched Jaw': {'Mokole': {'Noonday Sun': 4}},
    'Hand of the Earth Lords': {'Mokole': {'Noonday Sun': 4}},
    'Halo of the Sun': {'Mokole': {'Noonday Sun': 5}},
    
    # Mokole Midnight Sun Gifts
    'Brother\'s Scent': {'Mokole': {'Midnight Sun': 1}},
    'Sense Moon': {'Mokole': {'Midnight Sun': 1}},
    'Dreamspeak': {'Mokole': {'Midnight Sun': 2}},
    'Glib Tongue': {'Mokole': {'Midnight Sun': 2}},
    'Blissful Ignorance': {'Mokole': {'Midnight Sun': 3}},
    'Invisibility': {'Mokole': {'Midnight Sun': 3}},
    'Open Moon Bridge': {'Mokole': {'Midnight Sun': 3}},
    'Open Moon Bridge': {'Mokole': {'Midnight Sun': 3}},
    'Shadows by the Firelight': {'Mokole': {'Midnight Sun': 4}},
    'Take the True Form': {'Mokole': {'Midnight Sun': 5}},
    'Thousand Forms': {'Mokole': {'Midnight Sun': 5}},
    
    # Mokole Shrouded Sun Gifts
    'Tears of the Heavens': {'Mokole': {'Shrouded Sun': 1}},
    'Mother\'s Touch': {'Mokole': {'Shrouded Sun': 1}},
    'Sense Wyrm': {'Mokole': {'Shrouded Sun': 1}},
    'Sense Magic': {'Mokole': {'Shrouded Sun': 1}},
    'Spirit Speech': {'Mokole': {'Shrouded Sun': 1}},
    'Breaking the Tomorrow Wall': {'Mokole': {'Shrouded Sun': 2}},
    'Command Spirit': {'Mokole': {'Shrouded Sun': 2}},
    'Mental Speech': {'Mokole': {'Shrouded Sun': 2}},
    'Walking Between Worlds': {'Mokole': {'Shrouded Sun': 2}},
    'Open Moon Bridge': {'Mokole': {'Shrouded Sun': 3}},
    'Exorcism': {'Mokole': {'Shrouded Sun': 3}},
    'Spirit of the Bird': {'Mokole': {'Shrouded Sun': 3}},
    'Living Treasure': {'Mokole': {'Shrouded Sun': 4}},
    'Gorgon\'s Gaze': {'Mokole': {'Shrouded Sun': 5}},
    'Malleable Spirit': {'Mokole': {'Shrouded Sun': 5}},
    
    # Mokole Decorated Sun Gifts
    'Mercy': {'Mokole': {'Decorated Sun': 1}},
    'Pack Tactics': {'Mokole': {'Decorated Sun': 1}},
    'Persuasion': {'Mokole': {'Decorated Sun': 1}},
    'Cooking': {'Mokole': {'Decorated Sun': 1}},
    'Call to Duty': {'Mokole': {'Decorated Sun': 2}},
    'Command the Gathering': {'Mokole': {'Decorated Sun': 2}},
    'Walking Between Worlds': {'Mokole': {'Decorated Sun': 2}},
    'Reshape Object': {'Mokole': {'Decorated Sun': 3}},
    'Infest': {'Mokole': {'Decorated Sun': 4}},
    'Shadows by the Firelight': {'Mokole': {'Decorated Sun': 4}},
    'Chaos Mechanics': {'Mokole': {'Decorated Sun': 5}},
    'Obedience': {'Mokole': {'Decorated Sun': 5}},
    'Calm the Flock': {'Mokole': {'Decorated Sun': 5}},
    
    # Mokole Eclipsed Sun Gifts
    'Aura of Confidence': {'Mokole': {'Eclipsed Sun': 1}},
    'Heightened Senses': {'Mokole': {'Eclipsed Sun': 1}},
    'Lambent Flame': {'Mokole': {'Eclipsed Sun': 1}},
    'Dazzle': {'Mokole': {'Eclipsed Sun': 2}},
    'Walking Between Worlds': {'Mokole': {'Eclipsed Sun': 2}},
    'Icy Chill of Despair': {'Mokole': {'Eclipsed Sun': 3}},
    'Eye of the Cobra': {'Mokole': {'Eclipsed Sun': 3}},
    'Wrath of Gaia': {'Mokole': {'Eclipsed Sun': 3}},
    'Mastery': {'Mokole': {'Eclipsed Sun': 4}},
    'Halo of the Sun': {'Mokole': {'Eclipsed Sun': 5}},
    
    # Mokole Makara Gifts
    'Gift of the Spriggan': {'Mokole': {'Makara': 5}},
    
    # Mokole Zhong Lung Gifts
    'Mother\'s Touch': {'Mokole': {'Zhong Lung': 1}},
    
    # Mokole Shou Gifts
    'Serenity': {'Mokole': {'Shou': 4}},

    # Nagah General Gifts
    'Scent of Running Water': {'Nagah': 1},
    'Sense Wyrm': {'Nagah': 1},
    'Fatal Flaw': {'Nagah': 1},
    'Shed': {'Nagah': 1},
    'Burrow': {'Nagah': 2},
    'Mindspeak': {'Nagah': 2},
    'Pulse of the Prey': {'Nagah': 2},
    'Combat Healing': {'Nagah': 3},
    
    # Nagah Balaram Gifts
    'Persuasion': {'Nagah': {'Balaram': 1}},
    'Catfeet': {'Nagah': {'Balaram': 3}},
    'Spirit Ward': {'Nagah': {'Balaram': 4}},
    
    # Nagah Ahi Gifts
    'Rat Head': {'Nagah': {'Ahi': 1}},
    'Weaver Sense': {'Nagah': {'Ahi': 1}},
    'Weaver Sense': {'Nagah': {'Ahi': 1}},
    'Curse of Aeolus': {'Nagah': {'Ahi': 2}},
    'Venom Blood': {'Nagah': {'Ahi': 2}},
    'Call Elemental': {'Nagah': {'Ahi': 3}},
    'Divine Wind': {'Nagah': {'Ahi': 5}},
    
    # Nagah Vasuki Gifts
    'Scent of Sight': {'Nagah': {'Vasuki': 1}},
    'Form Mastery': {'Nagah': {'Vasuki': 2}},
    'Spirit of the Fray': {'Nagah': {'Vasuki': 2}},
    'Eye of the Cobra': {'Nagah': {'Vasuki': 3}},
    
    # Nagah Kamakshi (Spring) Gifts
    'Mother\'s Touch': {'Nagah': {'Kamakshi': 1}},
    'Resist Pain': {'Nagah': {'Kamakshi': 1}},
    'Brother\'s Scent': {'Nagah': {'Kamakshi': 1}},
    'Calm': {'Nagah': {'Kamakshi': 2}},
    'Dazzle': {'Nagah': {'Kamakshi': 3}},
    'Kali\'s Tongue': {'Nagah': {'Kamakshi': 4}},
    'Halo of the Sun': {'Nagah': {'Kamakshi': 5}},
    
    # Nagah Kartikeya (Summer) Gifts
    'Scent of the True Form': {'Nagah': {'Kartikeya': 1}},
    'Liar\'s Craft': {'Nagah': {'Kartikeya': 2}},
    'Blissful Ignorance': {'Nagah': {'Kartikeya': 2}},
    'Voice of the Mimic': {'Nagah': {'Kartikeya': 2}},
    'Might of Thor': {'Nagah': {'Kartikeya': 3}},
    'Stoking Fury\'s Furnace': {'Nagah': {'Kartikeya': 4}},
    'Phantasm': {'Nagah': {'Kartikeya': 4}},
    'Madness': {'Nagah': {'Kartikeya': 5}},
    
    # Nagah Kamsa (Autumn) Gifts
    'Seizing the Edge': {'Nagah': {'Kamsa': 1}},
    'Lightning Reflexes': {'Nagah': {'Kamsa': 1}},
    'Liar\'s Craft': {'Nagah': {'Kamsa': 2}},
    'Staredown': {'Nagah': {'Kamsa': 2}},
    'Eye of the Cobra': {'Nagah': {'Kamsa': 3}},
    'Doppelganger': {'Nagah': {'Kamsa': 4}},
    'Open Wounds': {'Nagah': {'Kamsa': 4}},
    'Head Games': {'Nagah': {'Kamsa': 5}},
    
    # Nagah Kali (Winter) Gifts
    'Falcon\'s Grasp': {'Nagah': {'Kali': 1}},
    'Weaver Sense': {'Nagah': {'Kali': 1}},
    'Weak Arm': {'Nagah': {'Kali': 2}},
    'Halt the Coward\'s Flight': {'Nagah': {'Kali': 2}},
    'Backbite': {'Nagah': {'Kali': 3}},
    'Coup de Grace': {'Nagah': {'Kali': 3}},
    'Mindblock': {'Nagah': {'Kali': 4}},
    'Chill of Early Frost': {'Nagah': {'Kali': 4}},
    'Heart of Ice': {'Nagah': {'Kali': 5}},

    # Nuwisha Gifts
    'Camouflage': {'Nuwisha': 1},
    'Laugh of the Hyena': {'Nuwisha': 1},
    'Speed of Thought': {'Nuwisha': 1},
    'Scent of Sweet Honey': {'Nuwisha': 1},
    'Shed': {'Nuwisha': 1},
    'Spirit Speech': {'Nuwisha': 1},
    'Man\'s Skin': {'Nuwisha': 1},
    'Two Tongues': {'Nuwisha': 1},
    'Command Spirit': {'Nuwisha': {'Umbral Danse': 2}},
    'Distractions': {'Nuwisha': 2},
    'Gift of the Termite': {'Nuwisha': 2},
    'Odious Aroma': {'Nuwisha': 2},
    'Spirit of the Fish': {'Nuwisha': 2},
    'Spirit of the Bird': {'Nuwisha': 3},
    'Umbral Camouflage': {'Nuwisha': {'Umbral Danse': 3}},
    'Pulse of the Invisible': {'Nuwisha': {'Umbral Danse': 3}},
    'Bridge Walker': {'Nuwisha': 4},
    'Grasp the Beyond': {'Nuwisha': {'Umbral Danse': 4}},
    'Blurring the Mirror': {'Nuwisha': {'Umbral Danse': 4}},
    'Phantasm': {'Nuwisha': 4},
    'Assimilation': {'Nuwisha': 5},
    'Fetish Doll': {'Nuwisha': 5},
    'Ultimate Argument of Logic': {'Nuwisha': 5},

    # Ratkin General Gifts
    'City Running': {'Ratkin': 1},
    'Resist Toxin': {'Ratkin': 1},
    'Spirit of the Lizard': {'Ratkin': 2},
    'Attunement': {'Ratkin': 4},
    'Gnaw': {'Ratkin': 4},
    'Riot': {'Ratkin': 5},
    'Survivor': {'Ratkin': 5},
    'Curse of Hatred': {'Ratkin': 2},
    'Shadow Weaving': {'Ratkin': 2},
    
    # Ratkin Homid Gifts
    'Cooking': {'Ratkin': {'Homid': 1}},
    'Odious Aroma': {'Ratkin': {'Homid': 1}},
    'Persuasion': {'Ratkin': {'Homid': 1}},
    'Reshape Object': {'Ratkin': {'Homid': 3}},
    'Blink': {'Ratkin': {'Homid': 4}},
    'Body Wrack': {'Ratkin': {'Homid': 4}},
    'Part the Veil': {'Ratkin': {'Homid': 5}},
    
    # Ratkin Metis Gifts
    'Form Mastery': {'Ratkin': {'Metis': 1}},
    'Mother\'s Touch': {'Ratkin': {'Metis': 1}},
    'Sense Wyrm': {'Ratkin': {'Metis': 1}},
    'Gift of the Porcupine': {'Ratkin': {'Metis': 2}},
    'Gift of the Skunk': {'Ratkin': {'Metis': 2}},
    'Rat Thing': {'Ratkin': {'Metis': 3}},
    'Sliver Tooth': {'Ratkin': {'Metis': 3}},
    'Rattler\'s Bite': {'Ratkin': {'Metis': 4}},
    'Whelp Body': {'Ratkin': {'Metis': 4}},
    'Song of the Great Beast': {'Ratkin': {'Metis': 5}},
    
    # Ratkin Rodens Gifts
    'Balance': {'Ratkin': {'Rodens': 1}},
    'Hare\'s Leap': {'Ratkin': {'Rodens': 1}},
    'Rat Thing': {'Ratkin': {'Rodens': 3}},
    'Sliver Tooth': {'Ratkin': {'Rodens': 3}},
    'Beast Life': {'Ratkin': {'Rodens': 4}},
    'Feral Lobotomy': {'Ratkin': {'Rodens': 5}},
    
    # Ratkin Tunnel Runner Gifts
    'Hotwire': {'Ratkin': {'Tunnel Runner': 2}},
    'Word Beyond': {'Ratkin': {'Tunnel Runner': 2}},
    'Bolt!': {'Ratkin': {'Tunnel Runner': 3}},
    'Flame Dance': {'Ratkin': {'Tunnel Runner': 3}},
    'Speech of the World': {'Ratkin': {'Tunnel Runner': 4}},
    
    # Ratkin Shadow Seer Gifts
    'Mother\'s Touch': {'Ratkin': {'Shadow Seer': 1}},
    'Sense Wyrm': {'Ratkin': {'Shadow Seer': 1}},
    'Sense Wyrm': {'Ratkin': {'Shadow Seer': 1}},
    'Name the Spirit': {'Ratkin': {'Shadow Seer': 2}},
    'Spirit Snare': {'Ratkin': {'Shadow Seer': 2}},
    'Command Spirit': {'Ratkin': {'Shadow Seer': 3}},
    'Exorcism': {'Ratkin': {'Shadow Seer': 3}},
    'Pulse of the Invisible': {'Ratkin': {'Shadow Seer': 4}},
    
    # Ratkin Knife Skulker Gifts
    'Fangs of Justice': {'Ratkin': {'Knife Skulker': 1}},
    'Truth of Gaia': {'Ratkin': {'Knife Skulker': 1}},
    'Snarl of the Predator': {'Ratkin': {'Knife Skulker': 2}},
    'Pulse of the Prey': {'Ratkin': {'Knife Skulker': 2}},
    'Doppelganger': {'Ratkin': {'Knife Skulker': 3}},
    'Paralyzing Stare': {'Ratkin': {'Knife Skulker': 3}},
    'Open Wounds': {'Ratkin': {'Knife Skulker': 4}},
    'Wither Limb': {'Ratkin': {'Knife Skulker': 4}},
    'Geas': {'Ratkin': {'Knife Skulker': 5}},
    
    # Ratkin Blade Slave Gifts
    'Fatal Flaw': {'Ratkin': {'Blade Slave': 1}},
    'Resist Pain': {'Ratkin': {'Blade Slave': 1}},
    'Razor Claws': {'Ratkin': {'Blade Slave': 1}},
    'Curse of Hatred': {'Ratkin': {'Blade Slave': 2}},
    'Spirit of the Fray': {'Ratkin': {'Blade Slave': 2}},
    'Bolt!': {'Ratkin': {'Blade Slave': 3}},
    'Improvisation': {'Ratkin': {'Blade Slave': 3}},
    'Preternatural Awareness': {'Ratkin': {'Blade Slave': 4}},
    'Circular Attack': {'Ratkin': {'Blade Slave': 5}},
    
    # Ratkin Engineer Gifts
    'Control Simple Machine': {'Ratkin': {'Engineer': 1}},
    'Open Seal': {'Ratkin': {'Engineer': 1}},
    'Trash is Treasure': {'Ratkin': {'Engineer': 1}},
    'Hotwire': {'Ratkin': {'Engineer': 2}},
    'Power Surge': {'Ratkin': {'Engineer': 2}},
    'Control Complex Machine': {'Ratkin': {'Engineer': 3}},
    'Electroshock': {'Ratkin': {'Engineer': 3}},
    
    # Ratkin Plague Lord Gifts
    'Primal Anger': {'Ratkin': {'Plague Lord': 1}},
    'Virulent Curse of Hatred': {'Ratkin': {'Plague Lord': 1}},
    'Dark of Night': {'Ratkin': {'Plague Lord': 2}},
    'Gift of the Skunk': {'Ratkin': {'Plague Lord': 2}},
    'Halt the Coward\'s Flight': {'Ratkin': {'Plague Lord': 3}},
    'Venom Blood': {'Ratkin': {'Plague Lord': 3}},
    
    # Ratkin Munchmausen Gifts
    'Persuasion': {'Ratkin': {'Munchmausen': 1}},
    'Spirit Speech': {'Ratkin': {'Munchmausen': 1}},
    'Liar\'s Craft': {'Ratkin': {'Munchmausen': 1}},
    'Name the Spirit': {'Ratkin': {'Munchmausen': 2}},
    'Umbral Camouflage': {'Ratkin': {'Munchmausen': 2}},
    'Improvisation': {'Ratkin': {'Munchmausen': 3}},
    'Phantasm': {'Ratkin': {'Munchmausen': 4}},
    
    # Ratkin Twitcher Gifts
    'Sense Wyrm': {'Ratkin': {'Twitcher': 1}},
    'Primal Anger': {'Ratkin': {'Twitcher': 1}},
    'Cornered Rat\'s Ferocity': {'Ratkin': {'Twitcher': 2}},
    'Jam Technology': {'Ratkin': {'Twitcher': 2}},
    'Gremlins': {'Ratkin': {'Twitcher': 3}},
    'Infest': {'Ratkin': {'Twitcher': 4}},

    # Rokea General Gifts
    'Hare\'s Leap': {'Rokea': 1},
    'Gift of the Porcupine': {'Rokea': 1},
    'Venom Blood': {'Rokea': 2},
    'Scent of Sight': {'Rokea': 2},
    'Troll Skin': {'Rokea': 2},
    'Trackless Waste': {'Rokea': 2},
    'Wyld Resurgence': {'Rokea': 2},
    'Resist Toxin': {'Rokea': 3},
    'Rat Head': {'Rokea': 3},
    'Avalanche': {'Rokea': 4},
    'Fenris\' Bite': {'Rokea': 4},
    'Song of the Great Beast': {'Rokea': 5},
    
    # Rokea Brightwater Gifts
    'Eyes of the Cat': {'Rokea': {'Brightwater': 1}},
    'Spur Claws': {'Rokea': {'Brightwater': 1}},
    'Shield of Rage': {'Rokea': {'Brightwater': 2}},
    'Wolf at the Door': {'Rokea': {'Brightwater': 2}},
    'Might of Thor': {'Rokea': {'Brightwater': 3}},
    'Heart Claw': {'Rokea': {'Brightwater': 3}},
    'Halo of the Sun': {'Rokea': {'Brightwater': 5}},
    
    # Rokea Dimwater Gifts
    'Resist Pain': {'Rokea': {'Dimwater': 1}},
    'Beast Speech': {'Rokea': {'Dimwater': 1}},
    'Sense the Unnatural': {'Rokea': {'Dimwater': 1}},
    'Truth of Gaia': {'Rokea': {'Dimwater': 1}},
    'King of the Beasts': {'Rokea': {'Dimwater': 2}},
    'Strike the Air': {'Rokea': {'Dimwater': 4}},
    
    # Rokea Darkwater Gifts
    'Shroud': {'Rokea': {'Darkwater': 1}},
    'Lightning Reflexes': {'Rokea': {'Darkwater': 1}},
    'Sight From Beyond': {'Rokea': {'Darkwater': 2}},
    'Direct the Storm': {'Rokea': {'Darkwater': 3}},
    'Shield of Gaia': {'Rokea': {'Darkwater': 5}},
    'Madness': {'Rokea': {'Darkwater': 5}},
    
    # Rokea Betweener Gifts
    'Spirit Speech': {'Rokea': {'Betweener': 1}},
    'Enter Sea\'s Soul': {'Rokea': {'Betweener': 2}},
    'Wall of Granite': {'Rokea': {'Betweener': 5}},
}