# Generated by Django 4.2.13 on 2025-05-21 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                (
                    "brief_description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description that appears on index pages (255 chars max).",
                        max_length=255,
                    ),
                ),
                (
                    "right_content",
                    models.TextField(
                        blank=True,
                        help_text="Optional content for the right sidebar. Leave empty to hide.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("featured_order", models.IntegerField(default=0)),
                ("is_index", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                (
                    "page_type",
                    models.IntegerField(
                        choices=[(0, "Regular"), (1, "Group"), (2, "Plot")], default=0
                    ),
                ),
                (
                    "lock_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Lock settings for this page. Format: {'has_splat': 'Vampire', 'has_clan': 'Brujah'}. Supported lock types: has_splat, has_type, has_clan, has_tribe, has_auspice, has_tradition, has_affiliation, has_convention, has_nephandi_faction, has_court, has_kith.",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user who created this page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        help_text="The last user to edit this page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mush_group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated MUSH Group (only for group pages)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_page",
                        to="groups.group",
                    ),
                ),
                ("related_to", models.ManyToManyField(blank=True, to="wiki.wikipage")),
            ],
            options={
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="WikiRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The content of this revision."),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the changes made in this revision.",
                        max_length=255,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="The user who made this revision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The wiki page this revision belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="wiki.wikipage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Revision",
                "verbose_name_plural": "Wiki Revisions",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload or provide URL for background image",
                        null=True,
                        upload_to="featured/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Upload or provide URL for banner image",
                        null=True,
                        upload_to="banners/",
                    ),
                ),
                (
                    "show_texture",
                    models.BooleanField(
                        default=True, help_text="Toggle the texture overlay on/off"
                    ),
                ),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_image",
                        to="wiki.wikipage",
                    ),
                ),
            ],
        ),
    ]
