# Generated by Django 4.2.16 on 2025-04-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_wikipage_published_alter_wikipage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="page_type",
            field=models.CharField(
                choices=[("regular", "Regular"), ("group", "Group"), ("plot", "Plot")],
                default="regular",
                help_text="Type of wiki page (regular, group, or plot)",
                max_length=10,
            ),
        ),
    ]
