# Generated by Django 4.2.16 on 2025-04-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_wikipage_page_type"),
        ("wiki", "add_custom_permissions"),
    ]

    operations = []
