# Generated by Django 4.2.16 on 2025-04-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_notes"),
        ("wiki", "0005_merge_0004_wikipage_page_type_add_custom_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipage",
            options={
                "ordering": ["title"],
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
            },
        ),
        migrations.AddField(
            model_name="wikipage",
            name="mush_group",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated MUSH Group (only for group pages)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_page",
                to="groups.group",
            ),
        ),
    ]
