# Generated by Django 4.2.16 on 2025-04-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_alter_wikipage_options_wikipage_mush_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="brief_description",
            field=models.CharField(
                blank=True,
                help_text="A brief description that appears on index pages (255 chars max).",
                max_length=255,
            ),
        ),
    ]
