# Generated by Django 4.2.16 on 2025-04-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_wikipage_brief_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="lock_settings",
            field=models.JSONField(
                blank=True, default=dict, help_text="Lock settings for this page"
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="is_index",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="page_type",
            field=models.IntegerField(
                choices=[(0, "Regular"), (1, "Group"), (2, "Plot")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="related_to",
            field=models.ManyToManyField(blank=True, to="wiki.wikipage"),
        ),
    ]
