# Generated by Django 4.2.16 on 2025-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0008_wikipage_lock_settings_alter_wikipage_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipage",
            name="lock_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Lock settings for this page. Format: {'has_splat': 'Vampire', 'has_clan': 'Brujah'}. Supported lock types: has_splat, has_type, has_clan, has_tribe, has_auspice, has_tradition, has_affiliation, has_convention, has_nephandi_faction, has_court, has_kith.",
            ),
        ),
    ]
