# Generated by Django 4.2.16 on 2025-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="guildmarks",
            field=models.CharField(
                blank=True,
                default="none",
                help_text="Type of guildmarks",
                max_length=200,
                null=True,
            ),
        ),
    ]
