# Generated by Django 4.2.16 on 2025-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0002_alter_stat_stat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="shifter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("garou", "Garou"),
                    ("gurahl", "Gurahl"),
                    ("rokea", "Rokea"),
                    ("ananasi", "Ananasi"),
                    ("ajaba", "Ajaba"),
                    ("bastet", "Bastet"),
                    ("corax", "Corax"),
                    ("kitsune", "Kitsune"),
                    ("mokole", "Mokole"),
                    ("nagah", "Nagah"),
                    ("nuwisha", "Nuwisha"),
                    ("ratkin", "Ratkin"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
    ]
