# Generated by Django 4.2.16 on 2025-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0003_stat_shifter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="auspice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ragabash", "Ragabash"),
                    ("theurge", "Theurge"),
                    ("philodox", "Philodox"),
                    ("galliard", "Galliard"),
                    ("ahroun", "Ahroun"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="breed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homid", "Homid"),
                    ("metis", "Metis"),
                    ("lupus", "Lupus"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="camp",
            field=models.CharField(
                blank=True,
                help_text="Specific camp that can learn this gift",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="source",
            field=models.CharField(
                blank=True, help_text="Source book reference", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="system",
            field=models.TextField(
                blank=True, help_text="Game mechanics description", null=True
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="tribe",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tribes that can learn this gift",
                null=True,
            ),
        ),
    ]
