# Generated by Django 4.2.16 on 2025-02-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0002_add_gift_alias"),
        ("wod20th", "0003_alter_stat_breed"),
    ]

    operations = []
