# Generated by Django 4.2.16 on 2025-02-21 23:50

from django.db import migrations, models
import json

def convert_to_json(apps, schema_editor):
    Stat = apps.get_model('wod20th', 'Stat')
    for stat in Stat.objects.all():
        if stat.shifter_type_old and stat.shifter_type_old != 'none':
            stat.shifter_type_new = [stat.shifter_type_old]
            stat.save()

class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0004_merge_0002_add_gift_alias_0003_alter_stat_breed"),
    ]

    operations = [
        # Add new field
        migrations.AddField(
            model_name='stat',
            name='shifter_type_new',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of shifter types that can learn this gift',
                null=True,
            ),
        ),
        # Rename old field
        migrations.RenameField(
            model_name='stat',
            old_name='shifter_type',
            new_name='shifter_type_old',
        ),
        # Copy data
        migrations.RunPython(
            convert_to_json,
            reverse_code=migrations.RunPython.noop,
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='stat',
            name='shifter_type_old',
        ),
        # Rename new field to final name
        migrations.RenameField(
            model_name='stat',
            old_name='shifter_type_new',
            new_name='shifter_type',
        ),
    ]
