# Generated by Django 4.2.16 on 2025-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0005_stat_mortalplus_type_alter_stat_stat_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stat",
            unique_together={("name", "stat_type")},
        ),
    ]
