# Generated by Django 4.2.16 on 2025-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0007_stat_prerequisites_stat_xp_cost_alter_stat_auspice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="xp_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
