# Generated by Django 4.2.16 on 2025-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0007_roster_rostermember"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="sphere",
            field=models.CharField(
                choices=[
                    ("mage", "Mage"),
                    ("vampire", "Vampire"),
                    ("werewolf", "Werewolf"),
                    ("changeling", "Changeling"),
                    ("hunter", "Hunter"),
                    ("wraith", "Wraith"),
                    ("demon", "Demon"),
                    ("mortal", "Mortal"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
