# Generated by Django 4.2.16 on 2025-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0017_alter_stat_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="auspice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("ragabash", "Ragabash"),
                    ("theurge", "Theurge"),
                    ("philodox", "Philodox"),
                    ("galliard", "Galliard"),
                    ("ahroun", "Ahroun"),
                    ("brightwater", "Brightwater"),
                    ("dimwater", "Dimwater"),
                    ("darkwater", "Darkwater"),
                    ("kamakshi", "Kamakshi"),
                    ("kartikeya", "Kartikeya"),
                    ("kamsa", "Kamsa"),
                    ("kali", "Kali"),
                    ("rising_sun", "Rising Sun"),
                    ("noonday_sun", "Noonday Sun"),
                    ("shrouded_sun", "Shrouded Sun"),
                    ("midnight_sun", "Midnight Sun"),
                    ("decorated_sun", "Decorated Sun"),
                    ("solar_eclipse", "Solar Eclipse"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stat",
            name="breed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("homid", "Homid"),
                    ("metis", "Metis"),
                    ("lupus", "Lupus"),
                    ("feline", "Feline"),
                    ("squamus", "Squamus"),
                    ("ursine", "Ursine"),
                    ("latrani", "Latrani"),
                    ("rodens", "Rodens"),
                    ("corvid", "Corvid"),
                    ("balaram", "Balaram"),
                    ("vasuki", "Vasuki"),
                    ("ahi", "Ahi"),
                    ("arachnid", "Arachnid"),
                    ("kojin", "Kojin"),
                    ("shinju", "Shinju"),
                    ("roko", "Roko"),
                    ("suchid", "Suchid"),
                ],
                default="none",
                max_length=100,
            ),
        ),
    ]
