# Generated by Django 4.2.16 on 2025-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0018_alter_stat_auspice_alter_stat_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="guildmarks",
            field=models.CharField(
                blank=True,
                default="none",
                help_text="Type of guildmarks",
                max_length=200,
            ),
        ),
    ]
