# Generated by Django 4.2.16 on 2025-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0019_stat_guildmarks"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stat",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stat",
            name="auspice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="breed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="stat",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="game_line",
            field=models.CharField(default="WoD20", max_length=50),
        ),
        migrations.AlterField(
            model_name="stat",
            name="shifter_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="splat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stat_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="stat",
            name="tribe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="values",
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name="stat",
            unique_together={("name", "category", "stat_type", "splat")},
        ),
        migrations.RemoveField(
            model_name="stat",
            name="camp",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="default",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="guildmarks",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="instanced",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="lock_string",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="mortalplus_type",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="source",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="system",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="xp_cost",
        ),
    ]
