# Generated by Django 4.2.16 on 2025-01-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("HIGH", "High"),
                    ("EXTREME", "Extreme"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
    ]
