# Generated by Django 4.2.13 on 2025-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plots", "0002_alter_plot_risk_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="related_situations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
