# Generated by Django 4.2.16 on 2025-01-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0015_crisis_outcome_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hangout",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
    ]
