# Generated by Django 4.2.16 on 2025-02-16 00:08

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HangoutDB",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
    ]
