# Generated by Django 4.2.16 on 2025-01-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_crisis_outcome_task"),
        ("hangouts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hangout",
        ),
        migrations.CreateModel(
            name="HangoutDB",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
    ]
