# Generated by Django 4.2.13 on 2025-05-22 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequential_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("resources", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("conceal", models.CharField(max_length=20)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("mundane", "Mundane"),
                            ("supernatural_consumable", "Supernatural Consumable"),
                            ("supernatural_unique", "Supernatural Unique"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ranged", "Ranged"),
                            ("melee", "Melee"),
                            ("improvised", "Improvised"),
                            ("thrown", "Thrown"),
                            ("explosives", "Explosives"),
                            ("ammunition", "Ammunition"),
                            ("technocratic", "Technocratic"),
                            ("martial_arts", "Martial Arts"),
                            ("spying", "Spying"),
                            ("communications", "Communications"),
                            ("survival", "Survival"),
                            ("electronics", "Electronics"),
                            ("aircraft", "Aircraft"),
                            ("landcraft", "Landcraft"),
                            ("seacraft", "Seacraft"),
                            ("talisman", "Talisman"),
                            ("device", "Device"),
                            ("trinket", "Trinket"),
                            ("gadget", "Gadget"),
                            ("invention", "Invention"),
                            ("matrix", "Matrix"),
                            ("grimoire", "Grimoire"),
                            ("biotech", "Biotech"),
                            ("cybertech", "Cybertech"),
                            ("periapt", "Periapt"),
                            ("chimerical", "Chimerical"),
                            ("treasure", "Treasure"),
                            ("fetish", "Fetish"),
                            ("talen", "Talen"),
                            ("artifact", "Artifact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_unique", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sequential_id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_proven", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.CharField(max_length=100)),
                ("max_speed", models.CharField(max_length=100)),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                (
                    "aircraft_type",
                    models.CharField(
                        choices=[
                            ("balloon", "Hot Air Balloon"),
                            ("helicopter", "Helicopter"),
                            ("prop_plane", "Propeller Plane"),
                            ("jet", "Jet"),
                            ("fighter", "Fighter Jet"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requires_specialty", models.BooleanField(default=False)),
                (
                    "specialty_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helicopter", "Helicopter"),
                            ("fighter_jet", "Fighter Jet"),
                            ("", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                ("passenger_protection", models.BooleanField(default=True)),
                ("requires_skill", models.CharField(default="Pilot", max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=0)),
                ("dexterity_penalty", models.IntegerField(default=0)),
                ("is_shield", models.BooleanField(default=False)),
                ("shield_bonus", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Biotech",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Chimerical",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ChimericalArmor",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=0)),
                ("dexterity_penalty", models.IntegerField(default=0)),
                ("is_shield", models.BooleanField(default=False)),
                ("shield_bonus", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ChimericalMelee",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ChimericalRanged",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("rate", models.CharField(max_length=100)),
                ("clip", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ChimericalThrown",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="CommunicationsDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("range", models.CharField(max_length=100)),
                ("encryption_level", models.PositiveIntegerField()),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Cybertech",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.CharField(max_length=100)),
                ("max_speed", models.CharField(max_length=100)),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ElectronicDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Explosive",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("blast_area", models.CharField(max_length=100)),
                ("blast_power", models.CharField(max_length=100)),
                ("burn", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Fetish",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Grimoire",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ImprovisedWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("break_chance", models.PositiveIntegerField(default=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Invention",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Jetpack",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
                ("maneuver", models.PositiveIntegerField()),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("requires_skill", models.CharField(default="Jetpack", max_length=100)),
                ("is_technomagickal", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Landcraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("mass_damage", models.PositiveIntegerField(default=1)),
                ("passenger_protection", models.PositiveIntegerField(default=0)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("bus", "Bus"),
                            ("rv", "RV"),
                            ("limo", "Limousine"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="MartialArtsWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("style_requirements", models.TextField(blank=True)),
                ("special_techniques", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Matrix",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="MeleeWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Periapt",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="RangedWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("rate", models.CharField(max_length=100)),
                ("clip", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Seacraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("speed", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="SpyingDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("function", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("stealth_rating", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="SurvivalGear",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("durability", models.PositiveIntegerField()),
                ("weather_resistance", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Talen",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Talisman",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="TechnocraticDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("power_level", models.PositiveIntegerField()),
                ("maintenance_required", models.BooleanField(default=True)),
                ("maintenance_interval", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ThrownWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Treasure",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Trinket",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ThrownWeaponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thrown_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnocraticDeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("power_level", models.PositiveIntegerField()),
                ("maintenance_required", models.BooleanField(default=True)),
                ("maintenance_interval", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technocratic_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurvivalGearDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("durability", models.PositiveIntegerField()),
                ("weather_resistance", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survival_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupernaturalItemDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supernatural_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpyingDeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("stealth_rating", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spying_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialAmmunitionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("effects", models.TextField()),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_ammo_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeacraftDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seacraft_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RangedWeaponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("rate", models.CharField(max_length=100)),
                ("clip", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranged_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ManyToManyField(
                        through="equipment.InventoryItem", to="equipment.equipment"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeleeWeaponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melee_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MartialArtsWeaponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("style_requirements", models.TextField(blank=True)),
                ("special_techniques", models.TextField(blank=True)),
                (
                    "difficulty_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Difficulty modifier for martial arts maneuvers",
                    ),
                ),
                (
                    "damage_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Damage modifier for martial arts maneuvers",
                    ),
                ),
                (
                    "enhanced_maneuvers",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of maneuvers enhanced by this weapon",
                    ),
                ),
                (
                    "style_compatibility",
                    models.CharField(
                        default="any",
                        help_text="Which martial arts styles this weapon works with (hard, soft, any)",
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="martial_arts_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandcraftDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("safe_speed", models.CharField(blank=True, max_length=100)),
                ("max_speed", models.CharField(blank=True, max_length=100)),
                ("maneuver", models.PositiveIntegerField(blank=True, null=True)),
                ("crew", models.CharField(blank=True, max_length=100)),
                ("durability", models.PositiveIntegerField(blank=True, null=True)),
                ("structure", models.PositiveIntegerField(blank=True, null=True)),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("car", "Car"),
                            ("suv", "SUV"),
                            ("bus", "Bus"),
                            ("tank", "Tank"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mass_damage", models.CharField(blank=True, max_length=100)),
                ("passenger_protection", models.CharField(blank=True, max_length=100)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landcraft_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JetpackDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("safe_speed", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
                ("maneuver", models.PositiveIntegerField()),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("requires_skill", models.CharField(default="Jetpack", max_length=100)),
                ("is_technomagickal", models.BooleanField(default=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jetpack_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.playerinventory",
            ),
        ),
        migrations.CreateModel(
            name="ImprovisedWeaponDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("break_chance", models.PositiveIntegerField(default=50)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvised_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExplosiveDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blast_area", models.CharField(max_length=100)),
                ("blast_power", models.CharField(max_length=100)),
                ("burn", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explosive_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElectronicDeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronic_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CycleDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("safe_speed", models.CharField(blank=True, max_length=100)),
                ("max_speed", models.CharField(blank=True, max_length=100)),
                ("maneuver", models.PositiveIntegerField(blank=True, null=True)),
                ("crew", models.CharField(blank=True, max_length=100)),
                ("durability", models.PositiveIntegerField(blank=True, null=True)),
                ("structure", models.PositiveIntegerField(blank=True, null=True)),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommunicationsDeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range", models.CharField(max_length=100)),
                ("encryption_level", models.PositiveIntegerField()),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArmorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=0)),
                ("dexterity_penalty", models.IntegerField(default=0)),
                ("is_shield", models.BooleanField(default=False)),
                ("shield_bonus", models.PositiveIntegerField(default=0)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armor_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AmmunitionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caliber", models.CharField(max_length=50)),
                ("damage_modifier", models.CharField(max_length=50)),
                ("special_effects", models.TextField(blank=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ammo_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AircraftDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("safe_speed", models.CharField(blank=True, max_length=100)),
                ("max_speed", models.CharField(blank=True, max_length=100)),
                ("maneuver", models.PositiveIntegerField(blank=True, null=True)),
                ("crew", models.CharField(blank=True, max_length=100)),
                ("durability", models.PositiveIntegerField(blank=True, null=True)),
                ("structure", models.PositiveIntegerField(blank=True, null=True)),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
                (
                    "aircraft_type",
                    models.CharField(
                        choices=[
                            ("balloon", "Hot Air Balloon"),
                            ("helicopter", "Helicopter"),
                            ("prop_plane", "Propeller Plane"),
                            ("jet", "Jet"),
                            ("fighter", "Fighter Jet"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requires_specialty", models.BooleanField(default=False)),
                ("specialty_type", models.CharField(blank=True, max_length=50)),
                ("passenger_protection", models.BooleanField(default=True)),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft_details",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialAmmunition",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("effects", models.TextField()),
                (
                    "compatible_weapons",
                    models.ManyToManyField(to="equipment.rangedweapon"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("caliber", models.CharField(max_length=50)),
                ("damage_modifier", models.CharField(max_length=50)),
                ("special_effects", models.TextField(blank=True)),
                (
                    "compatible_weapons",
                    models.ManyToManyField(to="equipment.rangedweapon"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
    ]
