# Generated by Django 4.2.16 on 2025-03-30 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("resources", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("conceal", models.CharField(max_length=20)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("mundane", "Mundane"),
                            ("supernatural_consumable", "Supernatural Consumable"),
                            ("supernatural_unique", "Supernatural Unique"),
                        ],
                        max_length=35,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("is_unique", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_proven", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("defense", models.CharField(max_length=100)),
                ("defense_type", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="MeleeWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="NaturalWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="RangedWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("rate", models.CharField(max_length=100)),
                ("clip", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="PlayerInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ManyToManyField(
                        through="equipment.InventoryItem", to="equipment.equipment"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.playerinventory",
            ),
        ),
    ]
