# Generated by Django 4.2.16 on 2025-03-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("ranged", "Ranged"),
                    ("melee", "Melee"),
                    ("improvised", "Improvised"),
                    ("thrown", "Thrown"),
                    ("explosives", "Explosives"),
                    ("ammunition", "Ammunition"),
                    ("technocratic", "Technocratic"),
                    ("martial_arts", "Martial Arts"),
                    ("spying", "Spying"),
                    ("communications", "Communications"),
                    ("survival", "Survival"),
                    ("electronics", "Electronics"),
                    ("aircraft", "Aircraft"),
                    ("landcraft", "Landcraft"),
                    ("seacraft", "Seacraft"),
                    ("talisman", "Talisman"),
                    ("device", "Device"),
                    ("trinket", "Trinket"),
                    ("gadget", "Gadget"),
                    ("invention", "Invention"),
                    ("matrix", "Matrix"),
                    ("grimoire", "Grimoire"),
                    ("biotech", "Biotech"),
                    ("cybertech", "Cybertech"),
                    ("periapt", "Periapt"),
                    ("chimerical", "Chimerical"),
                    ("treasure", "Treasure"),
                    ("fetish", "Fetish"),
                    ("talen", "Talen"),
                    ("artifact", "Artifact"),
                ],
                max_length=50,
            ),
        ),
    ]
