# Generated by Django 4.2.16 on 2025-03-31 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_equipment_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.CharField(max_length=100)),
                ("max_speed", models.CharField(max_length=100)),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                (
                    "aircraft_type",
                    models.CharField(
                        choices=[
                            ("balloon", "Hot Air Balloon"),
                            ("helicopter", "Helicopter"),
                            ("prop_plane", "Propeller Plane"),
                            ("jet", "Jet"),
                            ("fighter", "Fighter Jet"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requires_specialty", models.BooleanField(default=False)),
                (
                    "specialty_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helicopter", "Helicopter"),
                            ("fighter_jet", "Fighter Jet"),
                            ("", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                ("passenger_protection", models.BooleanField(default=True)),
                ("requires_skill", models.CharField(default="Pilot", max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("caliber", models.CharField(max_length=50)),
                ("damage_modifier", models.CharField(max_length=50)),
                ("special_effects", models.TextField(blank=True)),
                (
                    "compatible_weapons",
                    models.ManyToManyField(to="equipment.rangedweapon"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Biotech",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Chimerical",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="CommunicationsDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("range", models.CharField(max_length=100)),
                ("encryption_level", models.PositiveIntegerField()),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Cybertech",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.CharField(max_length=100)),
                ("max_speed", models.CharField(max_length=100)),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("requires_skill", models.CharField(default="Drive", max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ElectronicDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Explosive",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("blast_area", models.CharField(max_length=100)),
                ("blast_power", models.CharField(max_length=100)),
                ("burn", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Fetish",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Grimoire",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ImprovisedWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("break_chance", models.PositiveIntegerField(default=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Invention",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Jetpack",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
                ("maneuver", models.PositiveIntegerField()),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("requires_skill", models.CharField(default="Jetpack", max_length=100)),
                ("is_technomagickal", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Landcraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("safe_speed", models.PositiveIntegerField()),
                ("max_speed", models.PositiveIntegerField()),
                ("maneuver", models.PositiveIntegerField()),
                ("crew", models.CharField(max_length=100)),
                ("durability", models.PositiveIntegerField()),
                ("structure", models.PositiveIntegerField()),
                ("weapons", models.CharField(blank=True, max_length=100)),
                ("mass_damage", models.PositiveIntegerField(default=1)),
                ("passenger_protection", models.PositiveIntegerField(default=0)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("bus", "Bus"),
                            ("rv", "RV"),
                            ("limo", "Limousine"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="MartialArtsWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
                ("style_requirements", models.TextField(blank=True)),
                ("special_techniques", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Matrix",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Periapt",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Seacraft",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("speed", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="SpecialAmmunition",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("effects", models.TextField()),
                (
                    "compatible_weapons",
                    models.ManyToManyField(to="equipment.rangedweapon"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="SpyingDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("function", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("stealth_rating", models.PositiveIntegerField()),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="SurvivalGear",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("durability", models.PositiveIntegerField()),
                ("weather_resistance", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Talen",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Talisman",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="TechnocraticDevice",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_source", models.CharField(max_length=100)),
                ("power_level", models.PositiveIntegerField()),
                ("maintenance_required", models.BooleanField(default=True)),
                ("maintenance_interval", models.CharField(max_length=100)),
                ("special_features", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="ThrownWeapon",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("damage", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("difficulty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Treasure",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Trinket",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("power_level", models.PositiveIntegerField()),
                ("activation_requirements", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("special_effects", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("equipment.equipment",),
        ),
        migrations.RemoveField(
            model_name="armor",
            name="defense",
        ),
        migrations.RemoveField(
            model_name="armor",
            name="defense_type",
        ),
        migrations.AddField(
            model_name="armor",
            name="dexterity_penalty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="armor",
            name="is_shield",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="armor",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="armor",
            name="shield_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="NaturalWeapon",
        ),
    ]
