# Generated by Django 4.2.16 on 2025-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_equipment_options_equipment_sequential_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="landcraft",
            name="requires_skill",
            field=models.CharField(default="Drive", max_length=100),
        ),
    ]
